
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
    $(DIST)/sumo.pnct \
    $(DIST)/sumo.scene \

$(DIST)/sumo.scene : sumo.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "sumo.blend:Main" "$(DIST)/sumo.scene"

$(DIST)/sumo.pnct : sumo.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "sumo.blend:Main" "$(DIST)/sumo.pnct" 
